In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv("merged_hospital_data.csv")

In [ ]:
data.head()

,Hospital ID,Hospital Name,Hospital Type,City,State,Department,Department ID,Doctor,Nurses,Staff Count,...,Dept_Staff_Capacity_Derived,Admissions_Rate_%_Derived,Staff_Utilization_%_Derived,Bed_Occupancy_Rate_%,Bed_Occupancy_Rate_Calc,ICU_Occupancy_Rate_Calc,Staff_Utilization_Calc,Readmission_Flag,Transferred_Flag,Equipment_InUse_Flag
0,HOSP00016,C K Hospital,Private,Mumbai,Maharashtra,General Medicine,DEPT004,Dr. Arjun Sharma,12,257,...,598.0,0.0,43.0,0.2,0.2,80.6,43.0,0.0,0.0,0.0
1,HOSP00019,Cure Well Hospital,Private,Bengaluru,Karnataka,General Surgery,DEPT010,Dr. Sneha Rao,15,288,...,583.0,0.2,49.4,0.2,0.2,41.0,49.4,0.0,0.0,0.0
2,HOSP00004,Yashoda Hospital,Private,Hyderabad,Telangana,Pulmonology,DEPT005,Dr. Priya Reddy,20,181,...,590.0,0.0,30.7,0.2,0.2,23.7,30.7,0.0,0.0,1.0
3,HOSP00017,Dharma Hospital,Private,Delhi,Delhi,Pulmonology,DEPT005,Dr. Rahul Verma,23,170,...,597.0,0.2,28.5,0.4,0.4,67.7,28.5,0.0,1.0,0.0
4,HOSP00017,Dharma Hospital,Private,Delhi,Delhi,Icu,DEPT009,Dr. Priya Reddy,34,116,...,576.0,0.0,20.1,0.6,0.6,39.0,20.1,0.0,0.0,1.0

In [ ]:
data.isnull().sum()

Hospital ID                          0
Hospital Name                        0
Hospital Type                        0
City                                 0
State                                0
Department                           0
Department ID                        0
Doctor                               0
Nurses                               0
Staff Count                          0
Patient ID                           0
Patient Name                         0
Gender                               0
Age                                  0
Admission Date                       0
Discharge Date                       0
Diagnosis                            0
Treatment                            0
Medication                           0
Admission Type                       0
Test Result                          0
Blood Type                           0
Beds Available                       0
ICU Beds                             0
Bed Number                           0
Bed Occupied                         0
Equipment                            0
Length of Stay                       0
Room No                              0
Billing Amount                       0
Insurance Provider                   1
Readmission                          1
Dept_Bed_Capacity_Derived            1
Beds_Occupied_Count                  1
Equipment ID                         1
Equipment Number                     1
Equipment Status                     1
Equipment_Total_Inventory            1
Equipment_Usage_Duration_Hours       1
Transferred                          1
Transfer_From_Department             1
Transfer_To_Department               1
Transfer_Date                     6208
Number_of_Transfers                  1
Dept_ICU_Bed_Capacity_Derived        1
Dept_Staff_Capacity_Derived          1
Admissions_Rate_%_Derived            1
Staff_Utilization_%_Derived          1
Bed_Occupancy_Rate_%                 1
Bed_Occupancy_Rate_Calc              1
ICU_Occupancy_Rate_Calc              1
Staff_Utilization_Calc               1
Readmission_Flag                     1
Transferred_Flag                     1
Equipment_InUse_Flag                 1
dtype: int64

In [ ]:
data["Transfer_Date"]

0                       NaN
1                       NaN
2                       NaN
3       2025-09-17 00:00:00
4                       NaN
               ...
7532                    NaN
7533                    NaN
7534                    NaN
7535    2026-01-27 00:00:00
7536                    NaN
Name: Transfer_Date, Length: 7537, dtype: object

In [ ]:
data["Insurance Provider"] = data["Insurance Provider"].fillna(data["Insurance Provider"].mode()[0])

In [ ]:
data["Readmission"] = data["Readmission"].fillna(data["Readmission"].mode()[0])

In [ ]:
data["Dept_Bed_Capacity_Derived"] = data["Dept_Bed_Capacity_Derived"].fillna(data["Dept_Bed_Capacity_Derived"].mean())

In [ ]:
data["Beds_Occupied_Count"] = data["Beds_Occupied_Count"].fillna(data["Beds_Occupied_Count"].mode()[0])

In [ ]:
data["Equipment ID"] = data["Equipment ID"].fillna(data["Equipment ID"].mode()[0])

In [ ]:
data["Equipment Number"] = data["Equipment Number"].fillna(data["Equipment Number"].mode()[0])

In [ ]:
data["Equipment Status"] = data["Equipment Status"].fillna(data["Equipment Status"].mode()[0])

In [ ]:
data["Equipment_Total_Inventory"] = data["Equipment_Total_Inventory"].fillna(data["Equipment_Total_Inventory"].mean())

In [ ]:
data["Equipment_Usage_Duration_Hours"] = data["Equipment_Usage_Duration_Hours"].fillna(data["Equipment_Usage_Duration_Hours"].mean())

In [ ]:
data["Transferred"] = data["Transferred"].fillna(data["Transferred"].mode()[0])

In [ ]:
data["Transfer_From_Department"] = data["Transfer_From_Department"].fillna(data["Transfer_From_Department"].mode()[0])

In [ ]:
data["Transfer_To_Department"] = data["Transfer_To_Department"].fillna(data["Transfer_To_Department"].mode()[0])

In [ ]:
data["Number_of_Transfers"] = data["Number_of_Transfers"].fillna(data["Number_of_Transfers"].mean())

In [ ]:
data["Dept_ICU_Bed_Capacity_Derived"] = data["Dept_ICU_Bed_Capacity_Derived"].fillna(data["Dept_ICU_Bed_Capacity_Derived"].mean())

In [ ]:
data["Dept_Staff_Capacity_Derived"] = data["Dept_Staff_Capacity_Derived"].fillna(data["Dept_Staff_Capacity_Derived"].mean())

In [ ]:
data["Admissions_Rate_%_Derived"] = data["Admissions_Rate_%_Derived"].fillna(data["Admissions_Rate_%_Derived"].mean())

In [ ]:
data["Staff_Utilization_%_Derived"] = data["Staff_Utilization_%_Derived"].fillna(data["Staff_Utilization_%_Derived"].mean())

In [ ]:
data["Bed_Occupancy_Rate_%"] = data["Bed_Occupancy_Rate_%"].fillna(data["Bed_Occupancy_Rate_%"].mean())

In [ ]:
data["Bed_Occupancy_Rate_Calc"] = data["Bed_Occupancy_Rate_Calc"].fillna(data["Bed_Occupancy_Rate_Calc"].mean())

In [ ]:
data["ICU_Occupancy_Rate_Calc"] = data["ICU_Occupancy_Rate_Calc"].fillna(data["ICU_Occupancy_Rate_Calc"].mean())

In [ ]:
data["Staff_Utilization_Calc"] = data["Staff_Utilization_Calc"].fillna(data["Staff_Utilization_Calc"].mean())

In [ ]:
data["Readmission_Flag"] = data["Readmission_Flag"].fillna(data["Readmission_Flag"].mean())

In [ ]:
data["Transferred_Flag"] = data["Transferred_Flag"].fillna(data["Transferred_Flag"].mean())

In [ ]:
data["Equipment_InUse_Flag"] = data["Equipment_InUse_Flag"].fillna(data["Equipment_InUse_Flag"].mean())

In [62]:
data["Transfer_Date"] = pd.to_datetime(data["Transfer_Date"], errors='coerce')

In [63]:
data.head()

,Hospital ID,Hospital Name,Hospital Type,City,State,Department,Department ID,Doctor,Nurses,Staff Count,...,Dept_Staff_Capacity_Derived,Admissions_Rate_%_Derived,Staff_Utilization_%_Derived,Bed_Occupancy_Rate_%,Bed_Occupancy_Rate_Calc,ICU_Occupancy_Rate_Calc,Staff_Utilization_Calc,Readmission_Flag,Transferred_Flag,Equipment_InUse_Flag
0,HOSP00016,C K Hospital,Private,Mumbai,Maharashtra,General Medicine,DEPT004,Dr. Arjun Sharma,12,257,...,598.0,0.0,43.0,0.2,0.2,80.6,43.0,0.0,0.0,0.0
1,HOSP00019,Cure Well Hospital,Private,Bengaluru,Karnataka,General Surgery,DEPT010,Dr. Sneha Rao,15,288,...,583.0,0.2,49.4,0.2,0.2,41.0,49.4,0.0,0.0,0.0
2,HOSP00004,Yashoda Hospital,Private,Hyderabad,Telangana,Pulmonology,DEPT005,Dr. Priya Reddy,20,181,...,590.0,0.0,30.7,0.2,0.2,23.7,30.7,0.0,0.0,1.0
3,HOSP00017,Dharma Hospital,Private,Delhi,Delhi,Pulmonology,DEPT005,Dr. Rahul Verma,23,170,...,597.0,0.2,28.5,0.4,0.4,67.7,28.5,0.0,1.0,0.0
4,HOSP00017,Dharma Hospital,Private,Delhi,Delhi,Icu,DEPT009,Dr. Priya Reddy,34,116,...,576.0,0.0,20.1,0.6,0.6,39.0,20.1,0.0,0.0,1.0

In [66]:
data.to_csv("Final_clean_dataset.csv", index=False)