# Module 1 - Data Collection and Initial Inspection

## Project
MedTrack_DV (Hospital Operations & Patient Analytics Dashboard)

### Intern
Sanika Patil

### Objective
Load the raw hospital dataset and perform an initial inspection before data cleaning.

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_excel("Hospital_RawDataset_Updated.xlsx")

In [5]:
df.head()

,Hospital ID,Hospital Name,Hospital Type,City,State,Department,Department ID,Doctor,Nurses,Staff Count,...,Transferred,Transfer_From_Department,Transfer_To_Department,Transfer_Date,Number_of_Transfers,Dept_ICU_Bed_Capacity_Derived,Dept_Staff_Capacity_Derived,Admissions_Rate_%_Derived,Staff_Utilization_%_Derived,Bed_Occupancy_Rate_%
0,HOSP00016,C K Hospital,Private,Mumbai,Maharashtra,General Medicine,DEPT004,Dr. Arjun Sharma,12,257,...,No,General Medicine,NaN,NaN,0,98,598,0.0,43.0,0.2
1,HOSP00019,Cure Well Hospital,Private,Bengaluru,Karnataka,General Surgery,DEPT010,Dr. Sneha Rao,15,288,...,No,General Surgery,NaN,NaN,0,100,583,0.2,49.4,0.2
2,HOSP00004,Yashoda Hospital,Private,Hyderabad,Telangana,Pulmonology,DEPT005,Dr. Priya Reddy,20,181,...,No,Pulmonology,NaN,NaN,0,97,590,0.0,30.7,0.2
3,HOSP00017,Dharma Hospital,Private,Delhi,Delhi,Pulmonology,DEPT005,Dr. Rahul Verma,23,170,...,Yes,Pulmonology,Cardiology,9/17/2025,1,99,597,0.2,28.5,0.4
4,HOSP00017,Dharma Hospital,Private,Delhi,Delhi,ICU,DEPT009,Dr. Priya Reddy,34,116,...,No,ICU,NaN,NaN,0,100,576,0.0,20.1,0.6

In [6]:
print("Rows and Columns:")
df.shape

Rows and Columns:

(10000, 49)

In [7]:
print(df.columns.tolist())

['Hospital ID', 'Hospital Name', 'Hospital Type', 'City', 'State', 'Department', 'Department ID', 'Doctor', 'Nurses', 'Staff Count', 'Patient ID', 'Patient Name', 'Gender', 'Age', 'Admission Date', 'Discharge Date', 'Diagnosis', 'Treatment', 'Medication', 'Admission Type', 'Test Result', 'Blood Type', 'Beds Available', 'ICU Beds', 'Bed Number', 'Bed Occupied', 'Equipment', 'Length of Stay', 'Room No', 'Billing Amount', 'Insurance Provider', 'Readmission', 'Dept_Bed_Capacity_Derived', 'Beds_Occupied_Count', 'Equipment ID', 'Equipment Number', 'Equipment Status', 'Equipment_Total_Inventory', 'Equipment_Usage_Duration_Hours', 'Transferred', 'Transfer_From_Department', 'Transfer_To_Department', 'Transfer_Date', 'Number_of_Transfers', 'Dept_ICU_Bed_Capacity_Derived', 'Dept_Staff_Capacity_Derived', 'Admissions_Rate_%_Derived', 'Staff_Utilization_%_Derived', 'Bed_Occupancy_Rate_%']

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 49 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Hospital ID                     10000 non-null  str
 1   Hospital Name                   10000 non-null  str
 2   Hospital Type                   10000 non-null  str
 3   City                            10000 non-null  str
 4   State                           10000 non-null  str
 5   Department                      10000 non-null  str
 6   Department ID                   10000 non-null  str
 7   Doctor                          10000 non-null  str
 8   Nurses                          10000 non-null  int64
 9   Staff Count                     10000 non-null  int64
 10  Patient ID                      10000 non-null  str
 11  Patient Name                    10000 non-null  str
 12  Gender                          10000 non-null  str
 13  Age                             10000 non-null  int64
 14  Admission Date                  10000 non-null  object
 15  Discharge Date                  10000 non-null  object
 16  Diagnosis                       10000 non-null  str
 17  Treatment                       10000 non-null  str
 18  Medication                      10000 non-null  str
 19  Admission Type                  10000 non-null  str
 20  Test Result                     10000 non-null  str
 21  Blood Type                      10000 non-null  str
 22  Beds Available                  10000 non-null  int64
 23  ICU Beds                        10000 non-null  int64
 24  Bed Number                      10000 non-null  int64
 25  Bed Occupied                    10000 non-null  str
 26  Equipment                       10000 non-null  str
 27  Length of Stay                  10000 non-null  int64
 28  Room No                         10000 non-null  int64
 29  Billing Amount                  10000 non-null  int64
 30  Insurance Provider              7537 non-null   str
 31  Readmission                     10000 non-null  str
 32  Dept_Bed_Capacity_Derived       10000 non-null  int64
 33  Beds_Occupied_Count             10000 non-null  int64
 34  Equipment ID                    10000 non-null  str
 35  Equipment Number                10000 non-null  str
 36  Equipment Status                10000 non-null  str
 37  Equipment_Total_Inventory       10000 non-null  int64
 38  Equipment_Usage_Duration_Hours  10000 non-null  float64
 39  Transferred                     10000 non-null  str
 40  Transfer_From_Department        10000 non-null  str
 41  Transfer_To_Department          1760 non-null   str
 42  Transfer_Date                   1760 non-null   object
 43  Number_of_Transfers             10000 non-null  int64
 44  Dept_ICU_Bed_Capacity_Derived   10000 non-null  int64
 45  Dept_Staff_Capacity_Derived     10000 non-null  int64
 46  Admissions_Rate_%_Derived       10000 non-null  float64
 47  Staff_Utilization_%_Derived     10000 non-null  float64
 48  Bed_Occupancy_Rate_%            10000 non-null  float64
dtypes: float64(4), int64(15), object(3), str(27)
memory usage: 3.7+ MB

In [9]:
df.describe(include="all")

,Hospital ID,Hospital Name,Hospital Type,City,State,Department,Department ID,Doctor,Nurses,Staff Count,...,Transferred,Transfer_From_Department,Transfer_To_Department,Transfer_Date,Number_of_Transfers,Dept_ICU_Bed_Capacity_Derived,Dept_Staff_Capacity_Derived,Admissions_Rate_%_Derived,Staff_Utilization_%_Derived,Bed_Occupancy_Rate_%
count,10000,10000,10000,10000,10000,10000,10000,10000,10000.00000,10000.000000,...,10000,10000,1760,1760,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000
unique,20,20,2,6,6,10,10,4,NaN,NaN,...,2,10,10,523,NaN,NaN,NaN,NaN,NaN,NaN
top,HOSP00012,Medindia Hospital,Private,Chennai,Tamil Nadu,Neurology,DEPT002,Dr. Rahul Verma,NaN,NaN,...,No,Neurology,Psychiatry,2026-03-02 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN
freq,532,532,8496,1706,1706,1033,1033,2556,NaN,NaN,...,8240,1033,190,13,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.53610,341.421000,...,NaN,NaN,NaN,NaN,0.245800,98.701000,589.466100,0.110160,57.924860,0.36757
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.24947,149.201603,...,NaN,NaN,NaN,NaN,0.595834,1.743704,10.151047,0.109845,25.296697,0.18417
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.00000,80.000000,...,NaN,NaN,NaN,NaN,0.000000,86.000000,554.000000,0.000000,13.300000,0.20000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.00000,214.750000,...,NaN,NaN,NaN,NaN,0.000000,98.000000,584.000000,0.000000,36.375000,0.20000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.00000,343.000000,...,NaN,NaN,NaN,NaN,0.000000,99.000000,593.000000,0.200000,58.200000,0.40000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39.00000,470.000000,...,NaN,NaN,NaN,NaN,0.000000,100.000000,598.000000,0.200000,79.600000,0.40000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.00000,600.000000,...,NaN,NaN,NaN,NaN,3.000000,100.000000,600.000000,0.600000,100.000000,1.40000

In [10]:
df.isnull().sum()

Hospital ID                          0
Hospital Name                        0
Hospital Type                        0
City                                 0
State                                0
Department                           0
Department ID                        0
Doctor                               0
Nurses                               0
Staff Count                          0
Patient ID                           0
Patient Name                         0
Gender                               0
Age                                  0
Admission Date                       0
Discharge Date                       0
Diagnosis                            0
Treatment                            0
Medication                           0
Admission Type                       0
Test Result                          0
Blood Type                           0
Beds Available                       0
ICU Beds                             0
Bed Number                           0
Bed Occupied                         0
Equipment                            0
Length of Stay                       0
Room No                              0
Billing Amount                       0
Insurance Provider                2463
Readmission                          0
Dept_Bed_Capacity_Derived            0
Beds_Occupied_Count                  0
Equipment ID                         0
Equipment Number                     0
Equipment Status                     0
Equipment_Total_Inventory            0
Equipment_Usage_Duration_Hours       0
Transferred                          0
Transfer_From_Department             0
Transfer_To_Department            8240
Transfer_Date                     8240
Number_of_Transfers                  0
Dept_ICU_Bed_Capacity_Derived        0
Dept_Staff_Capacity_Derived          0
Admissions_Rate_%_Derived            0
Staff_Utilization_%_Derived          0
Bed_Occupancy_Rate_%                 0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.dtypes

Hospital ID                           str
Hospital Name                         str
Hospital Type                         str
City                                  str
State                                 str
Department                            str
Department ID                         str
Doctor                                str
Nurses                              int64
Staff Count                         int64
Patient ID                            str
Patient Name                          str
Gender                                str
Age                                 int64
Admission Date                     object
Discharge Date                     object
Diagnosis                             str
Treatment                             str
Medication                            str
Admission Type                        str
Test Result                           str
Blood Type                            str
Beds Available                      int64
ICU Beds                            int64
Bed Number                          int64
Bed Occupied                          str
Equipment                             str
Length of Stay                      int64
Room No                             int64
Billing Amount                      int64
Insurance Provider                    str
Readmission                           str
Dept_Bed_Capacity_Derived           int64
Beds_Occupied_Count                 int64
Equipment ID                          str
Equipment Number                      str
Equipment Status                      str
Equipment_Total_Inventory           int64
Equipment_Usage_Duration_Hours    float64
Transferred                           str
Transfer_From_Department              str
Transfer_To_Department                str
Transfer_Date                      object
Number_of_Transfers                 int64
Dept_ICU_Bed_Capacity_Derived       int64
Dept_Staff_Capacity_Derived         int64
Admissions_Rate_%_Derived         float64
Staff_Utilization_%_Derived       float64
Bed_Occupancy_Rate_%              float64
dtype: object

In [13]:
df.to_csv("Hospital_RawDataset.csv", index=False)