# Module 3 - KPI Engineering

## Project
Hospital Operations & Patient Analytics Dashboard

### Objective

The objective of this module is to engineer business Key Performance Indicators (KPIs) from the cleaned hospital dataset. These KPIs will be used in the Tableau dashboards developed in later modules.

### Dataset

hospital_cleaned.csv

### Tools Used

- Python
- Pandas
- NumPy

### Output

hospital_kpi_dataset.csv

## Importing libraries and dataset

In [35]:
import pandas as pd
import numpy as np

df = pd.read_csv("hospital_cleaned.csv")

print("Dataset Shape:", df.shape)

print("\nColumns:\n")

for col in df.columns:
    print(col)

Dataset Shape: (10000, 55)

Columns:

Hospital ID
Hospital Name
Hospital Type
City
State
Department
Department ID
Doctor
Nurses
Staff Count
Patient ID
Patient Name
Gender
Age
Admission Date
Discharge Date
Diagnosis
Treatment
Medication
Admission Type
Test Result
Blood Type
Beds Available
ICU Beds
Bed Number
Bed Occupied
Equipment
Length of Stay
Room No
Billing Amount
Insurance Provider
Readmission
Dept_Bed_Capacity_Derived
Beds_Occupied_Count
Equipment ID
Equipment Number
Equipment Status
Equipment_Total_Inventory
Equipment_Usage_Duration_Hours
Transferred
Transfer_From_Department
Transfer_To_Department
Transfer_Date
Number_of_Transfers
Dept_ICU_Bed_Capacity_Derived
Dept_Staff_Capacity_Derived
Admissions_Rate_%_Derived
Staff_Utilization_%_Derived
Bed_Occupancy_Rate_%
Bed_Occupancy_Rate_Calc
ICU_Occupancy_Rate_Calc
Staff_Utilization_Calc
Readmission_Flag
Transferred_Flag
Equipment_InUse_Flag

## Dataset Overview

In [44]:
print(df.shape)

df.info()

(10000, 55)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 55 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Hospital ID                     10000 non-null  object
 1   Hospital Name                   10000 non-null  object
 2   Hospital Type                   10000 non-null  object
 3   City                            10000 non-null  object
 4   State                           10000 non-null  object
 5   Department                      10000 non-null  object
 6   Department ID                   10000 non-null  object
 7   Doctor                          10000 non-null  object
 8   Nurses                          10000 non-null  int64
 9   Staff Count                     10000 non-null  int64
 10  Patient ID                      10000 non-null  object
 11  Patient Name                    10000 non-null  object
 12  Gender                          10000 non-null  object
 13  Age                             10000 non-null  int64
 14  Admission Date                  6078 non-null   object
 15  Discharge Date                  6056 non-null   object
 16  Diagnosis                       10000 non-null  object
 17  Treatment                       10000 non-null  object
 18  Medication                      10000 non-null  object
 19  Admission Type                  10000 non-null  object
 20  Test Result                     10000 non-null  object
 21  Blood Type                      10000 non-null  object
 22  Beds Available                  10000 non-null  int64
 23  ICU Beds                        10000 non-null  int64
 24  Bed Number                      10000 non-null  int64
 25  Bed Occupied                    10000 non-null  object
 26  Equipment                       10000 non-null  object
 27  Length of Stay                  10000 non-null  int64
 28  Room No                         10000 non-null  int64
 29  Billing Amount                  10000 non-null  int64
 30  Insurance Provider              10000 non-null  object
 31  Readmission                     10000 non-null  object
 32  Dept_Bed_Capacity_Derived       10000 non-null  int64
 33  Beds_Occupied_Count             10000 non-null  int64
 34  Equipment ID                    10000 non-null  object
 35  Equipment Number                10000 non-null  object
 36  Equipment Status                10000 non-null  object
 37  Equipment_Total_Inventory       10000 non-null  int64
 38  Equipment_Usage_Duration_Hours  10000 non-null  float64
 39  Transferred                     10000 non-null  object
 40  Transfer_From_Department        10000 non-null  object
 41  Transfer_To_Department          10000 non-null  object
 42  Transfer_Date                   1068 non-null   object
 43  Number_of_Transfers             10000 non-null  int64
 44  Dept_ICU_Bed_Capacity_Derived   10000 non-null  int64
 45  Dept_Staff_Capacity_Derived     10000 non-null  int64
 46  Admissions_Rate_%_Derived       10000 non-null  float64
 47  Staff_Utilization_%_Derived     10000 non-null  float64
 48  Bed_Occupancy_Rate_%            10000 non-null  float64
 49  Bed_Occupancy_Rate_Calc         10000 non-null  float64
 50  ICU_Occupancy_Rate_Calc         10000 non-null  float64
 51  Staff_Utilization_Calc          10000 non-null  float64
 52  Readmission_Flag                10000 non-null  int64
 53  Transferred_Flag                10000 non-null  int64
 54  Equipment_InUse_Flag            10000 non-null  int64
dtypes: float64(7), int64(18), object(30)
memory usage: 4.2+ MB

## Summary Statistics

In [47]:
df.describe(include='all')

,Hospital ID,Hospital Name,Hospital Type,City,State,Department,Department ID,Doctor,Nurses,Staff Count,...,Dept_Staff_Capacity_Derived,Admissions_Rate_%_Derived,Staff_Utilization_%_Derived,Bed_Occupancy_Rate_%,Bed_Occupancy_Rate_Calc,ICU_Occupancy_Rate_Calc,Staff_Utilization_Calc,Readmission_Flag,Transferred_Flag,Equipment_InUse_Flag
count,10000,10000,10000,10000,10000,10000,10000,10000,10000.00000,10000.000000,...,10000.000000,10000.000000,10000.000000,10000.00000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
unique,20,20,2,6,6,10,10,4,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,HOSP00012,Medindia Hospital,Private,Chennai,Tamil Nadu,Neurology,DEPT002,Dr. Rahul Verma,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,532,532,8496,1706,1706,1033,1033,2556,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.53610,341.421000,...,589.466100,0.110160,57.924860,0.36757,0.36757,53.368830,57.924860,0.498700,0.176000,0.335500
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.24947,149.201603,...,10.151047,0.109845,25.296697,0.18417,0.18417,28.085722,25.296697,0.500023,0.380839,0.472189
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.00000,80.000000,...,554.000000,0.000000,13.300000,0.20000,0.20000,5.000000,13.300000,0.000000,0.000000,0.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.00000,214.750000,...,584.000000,0.000000,36.375000,0.20000,0.20000,29.000000,36.375000,0.000000,0.000000,0.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.00000,343.000000,...,593.000000,0.200000,58.200000,0.40000,0.40000,53.600000,58.200000,0.000000,0.000000,0.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39.00000,470.000000,...,598.000000,0.200000,79.600000,0.40000,0.40000,77.800000,79.600000,1.000000,0.000000,1.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.00000,600.000000,...,600.000000,0.600000,100.000000,1.40000,1.40000,100.000000,100.000000,1.000000,1.000000,1.000000

## KPI Engineering

KPI 1: 
Total Patients

In [51]:

df["Total_Admissions"] = len(df)

KPI 2:
 Average Length of Stay

In [54]:
# Average Length of Stay

avg_los = round(df["Length of Stay"].mean(),2)

df["Average_Length_of_Stay"] = avg_los

KPI 3 : Overall Occupancy Rate

In [57]:
# Overall Occupancy Rate

overall_occ = round(
    (df["Bed Occupied"].eq("Yes").mean())*100,
    2
)

df["Overall_Occupancy_Rate"] = overall_occ

KPI 4:
Readmission Rate

In [60]:
# Readmission Rate

read_rate = round(
    (df["Readmission"].eq("Yes").mean())*100,
    2
)

df["Readmission_Rate"] = read_rate

KPI 5: Bed Utilization Rate

In [63]:
# Bed Utilization Rate

bed_util = round(
    (df["Bed Occupied"].eq("Yes").mean())*100,
    2
)

df["Bed_Utilization_Rate"] = bed_util

KPI 6: Department Efficiency Score

In [76]:
# Department Efficiency Score

dept_eff = (
    df.groupby("Department")["Length of Stay"]
      .transform("mean")
)

dept_eff = (
    100 /
    dept_eff
).round(2)

df["Department_Efficiency_Score"] = dept_eff

## Validation of KPIs

In [70]:
kpi_summary = pd.DataFrame({

    "KPI":[

        "Total Admissions",

        "Average Length of Stay",

        "Overall Occupancy Rate",

        "Readmission Rate",

        "Bed Utilization Rate"

    ],

    "Value":[

        len(df),

        avg_los,

        f"{overall_occ}%",

        f"{read_rate}%",

        f"{bed_util}%"

    ]

})

kpi_summary

                      KPI   Value
0        Total Admissions   10000
1  Average Length of Stay    8.07
2  Overall Occupancy Rate  50.36%
3        Readmission Rate  49.87%
4    Bed Utilization Rate  50.36%

## Export final Dataset

In [73]:
df.to_excel(
    "hospital_final_dataset.xlsx",
    index=False
)

print("hospital_final_dataset.xlsx generated successfully.")

hospital_final_dataset.xlsx generated successfully.